services:
  - type: web
    name: image-converter-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGIN
        value: "*"
